// Export-to-TypeScript serializer (US-97). Produces a code block the operator
// pastes into `src/data/areas/<id>.ts` to replace the existing terrain and
// objects fields. Does NOT write to disk — the editor is read-mostly; paste-
// back is the human-controlled commit point.

import type { TerrainId } from '@game/maps/terrain';
import type { ObjectInstance } from '@game/maps/objects';

export function serializeTerrainAndObjects(
  terrain: TerrainId[][],
  objects: ObjectInstance[],
): string {
  const lines: string[] = [];
  lines.push('  // ───── Generated by tools/editor (US-97 Export TypeScript) ─────');
  lines.push('  terrain: [');
  for (const row of terrain) {
    lines.push('    [' + row.map((t) => `'${t}'`).join(', ') + '],');
  }
  lines.push('  ],');
  lines.push('  objects: [');
  for (const o of objects) {
    const condFragment = o.condition ? `, condition: '${o.condition}'` : '';
    lines.push(`    { kind: '${o.kind}', col: ${o.col}, row: ${o.row}${condFragment} },`);
  }
  lines.push('  ],');
  return lines.join('\n');
}
